### ISSUE TITLE
New CEs

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/themes_gridelements#11]
* modal
* panel
* button to trigger modal

**Comment by Bunnyfield** [comment]
Panel is ready now - implemented as a container "singleColumnHeaderFooter" AND as a replacement for the original "bullets" element - the first one is a real container with headline output and content areas for body and footer, the latter can be used i.e. for the famous pricing tables.

**Comment by Bunnyfield** [comment]
Buttons are now available as well. The simple buttons can be inserted as link classes directly with the link wizard within the RTE. More complex buttons are available as an own content element that can either have its own link or hold a group of link records that will create a drop down when rendering.
