### ISSUE TITLE
Karussell übernimmt die Klasse hidden-xs nicht

### ISSUE THREAD

**Issue by allesroger** [typo3-themes/themes_gridelements#14]
Das Karussell übernimmt beim Klick im Backend Mobil Hidden, die Bootstrap Klasse hidden-xs nicht.

**Comment by kaystrobach** [comment]
betrifft das nur xs oder auch andere?
habt ihr die neueste version?

**Comment by allesroger** [comment]
vor einer Stunde gepullt, die anderen Einstellungen noch nicht ausprobiert.

**Comment by kaystrobach** [comment]
bitte einfach nochmal pullen :smile:

**Comment by Bunnyfield** [comment]
Genaugenommen übernimmt es überhaupt keine der Klassen aus "responsive settings" kümmere ich mich gleich drum

**Comment by Bunnyfield** [comment]
Sollte jetzt gehen
