### ISSUE TITLE
multicolumn just allow single column children

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/themes_gridelements#15]

**Comment by Bunnyfield** [comment]
Is this a feature request, bug report ... ?

**Comment by kaystrobach** [comment]
IMHO this is intended behaviour, as you should nest it like:

* multicolumn
 * column
   * text/image
 * column
   * other content

The idea is to have a surrounding row (multicolumn) and then as many as you want columns and then content inside of these columns.
All the spreading options are set in the columns.

Feel free to reopen this issues, if you do not agree.
Regards
Kay
