### ISSUE TITLE
3 Columns rendering order

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes_gridelements#16]
Hi,
3Columns rendering order seem to be wrong.
In the pagets setup, the order of columns is (colPos) 2,0,1
The 2 and 4 columns follow logical order : 0,1,2,3
Either change the listNum of setupts according or adjust colPos

**Comment by Bunnyfield** [comment]
Actually the problem was a wrong order in the list of classes in the flexform - fixed in master

**Comment by Bunnyfield** [comment]
2,0,1 has been done on purpose to have the "middle" column as the main column - is a bit tricky with an even number of columns, since there is no middle column then ;-)

**Comment by Bunnyfield** [comment]
no objections - closing the issue
