### ISSUE TITLE
Container behiavour

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes_gridelements#17]
Hi all,
"Containers can be used to breakup default structures and have elements use the whole viewport width instead of the limited grid."

This is wrong (at least in bootstrap) 
Once there is a .container, the childrens can't break up layout and use the whole viewport.
With .container, the width is fixed to the container width defined in bootstrap, and .container-fluid take the 100% width of her parent.

The only way to "break up layout" is not having any layout,  using container where you want one, and not where you want a full screen width.

A "clean layout" (with top menu) but without any .container in body may be a good solution for such designs.

**Comment by Bunnyfield** [comment]
Reading the container section http://getbootstrap.com/css/#grid gives me another information.

The container determines the width of a row somewhere between fixed and full, so you can use containers to do exactly what has been described in the text.

With one exception though: When you are using a page layout that already uses a .container class, you can not get more than the width determined by that container. Officially containers are not to be nested, but still that works somehow.

**Comment by s-leger** [comment]
You're right, It's all about nesting.

* .container-fluid : full mean 100% of the parent, so not the viewport when nested.
* .container nesting don't change behaviour, sice it has a fixed width (not for all breakpoints).

As far as i can see, vast majority of layouts currently use .container. This is exactly why we need a "clean" layout without any .container, but with a top menu, or maybe better menu contents elements to use with empty layout.

**Comment by kaystrobach** [comment]
imho there is "special" for that

**Comment by s-leger** [comment]
Good, 
haven't see it since it is disabled in theme_bootstrap

**Comment by kaystrobach** [comment]
No should be in bootstrap, just take a look in the Backend layouts of a page
