### ISSUE TITLE
Register mess in Tab container ?

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes_gridelements#18]
Hi, 
This is related to gridelements in general.
Seem register in Tabs preCObject dosen't have a restore ?

I'm getting one more depth level in register after Tab content element.

**Comment by Bunnyfield** [comment]
yep - there must be a restore at least after the tab has been rendered, maybe even earlier. - Will push something tonight.

**Comment by Bunnyfield** [comment]
Please check the latest version - should be fixed now.
