### ISSUE TITLE
Single Column is missing.

### ISSUE THREAD

**Issue by evilknevil10** [typo3-themes/themes_gridelements#24]
Single Column is missing in the actual Themes. Only Column/Panel is there, but it is rendering the wrong HTML output for Bootstrap.

**Comment by kaystrobach** [comment]
Is the problem reproduceable with one of the official themes? E.g. highland or mosaic, just used it yesterday with mosaic ... :smiley:

**Comment by evilknevil10** [comment]
yes it is the same problem. i just installed mosaic. the rendering of html is not correct.

https://www.evernote.com/l/ATivKPB0rGBMOqjLu1jd1FzYyRCPEVVxlj8B/image.png

**Comment by Bunnyfield** [comment]
Could you please give a screenshot of your backend and the available gridelements as well?
There should be singleColumn, singleColumnHeaderFooter and singleColumnHorizontal in the latest themes_gridelements so I don't know exactly what we should "put back"

**Comment by Bunnyfield** [comment]
![examplehighland](https://cloud.githubusercontent.com/assets/3198454/8511398/7e980ab6-2314-11e5-8506-34a27b67e101.png)

This is a screenshot of a current installation of Theme Bootstrap Highland - no problems visible so far.

**Comment by kaystrobach** [comment]
* custom pagets anywhere?
* which versions do you have installed?
* have you manipulated one of the extensions?

**Comment by kaystrobach** [comment]
* have you uploaded the extensions via FTP? if so have you rechecked the file integrity - ftp does not provided that by default, it's more like fire and forget uploads.

**Comment by evilknevil10** [comment]
ok you can reproduce the wrong html with the following:

Take grid "container". save. put in the "container" a grid element "row". Save. Put in the grid "row"  a grid "Column/Panel (Horizontal)" save. put in there a CE "Header". Save and look at the code. Then you have it.

**Comment by kaystrobach** [comment]
i think @Bunnyfield and me just tested your first problem of missing single column only.

__PLEASE always provide a single problem per Issue__ :smiley:

**Comment by Bunnyfield** [comment]
Exactly :-)

Single Column (Vertical) is still there and Single Column Horizontal has been added.
So your actual problem is a bug in the rendering of the horizontal column variant.

**Comment by evilknevil10** [comment]
Ok. but when you delete the Single Column and take it again, the code is correct ;-)

**Comment by kaystrobach** [comment]
so #24 and #25 can be closed?

**Comment by Bunnyfield** [comment]
No - there seems to be a problem as described in #25 - so #24 can be closed since the single column is not missing at all, but #25 must be fixed
