### ISSUE TITLE
2col Grid cannot be edit

### ISSUE THREAD

**Issue by evilknevil10** [typo3-themes/themes_gridelements#26]
When you take a 2col / 3col or 4col grid. you can´t edit the grids itself. Blank Site.

See here 

https://www.evernote.com/l/ATjieFysfg5F-LikyxGmNGK7XlmhorZG_LEB/image.png

Andre

**Comment by Bunnyfield** [comment]
Can not reproduce that with current themes_gridelements - are you sure there are no other content elements involved? Blank site usually means PHP error - so the probem could be in one of the editing forms of a plugin. Please test the same containers with default content elements.

**Comment by kaystrobach** [comment]
still valid:

* http://www.dmitry-dulepov.com/2009/03/blank-empty-page-in-typo3.html

feel free to reopen, if still reproduceable for you!
