### ISSUE TITLE
Responsive Steps

### ISSUE THREAD

**Issue by baschte** [typo3-themes/themes_gridelements#27]
Responsive Steps on Accordeon & Slider are missing. ClassMapping

**Comment by kaystrobach** [comment]
What do you mean by responsive steps?

What do you expect exactly?

**Comment by 2kone** [comment]
Hey Kay,
Thomas knows what i mean.

If i choose a Slider or Accordein Gridelement and want that this Element isnt visible on Mobile or Tablet the Classes were not added to that Element.

**Comment by Bunnyfield** [comment]
Slider should be available, since there is
responsiveMapping =< lib.content.cssMap.responsive
in the Carousel.setupts

**Comment by Bunnyfield** [comment]
Just pushed accordion responsive mapping

**Comment by Bunnyfield** [comment]
Can this one be closed, or is there still something missing in Carousels?

**Comment by kaystrobach** [comment]
@baschte resolved?

**Comment by baschte** [comment]
@kaystrobach yes, solved :-)

**Comment by tdeuling** [comment]
This problem remains?!
Just heard this problem still exists in 0.6.3. - we have to check this.

**Comment by tdeuling** [comment]
Solved. Additionally we're now providing a new inList viewhelper, for checking if a variant or behaviour is set.
See: https://github.com/typo3-themes/themes_gridelements/blob/master/Resources/Private/Templates/Elements/Accordion.html#L41
