### ISSUE TITLE
Links in carousel-indicators are not working!

### ISSUE THREAD

**Issue by Starraider** [typo3-themes/themes_gridelements#28]
In themes_gridelements/Resources/Private/Templates/Elements/Carousel.html
Line 15 should be:  
```
<li data-target="#c{data.uid}" data-slide-to="{indicator.index}"{f:if(condition:'{indicator.isFirst}',then:' class="active"')}></li>
```

With data-target="#carousel-{data.uid}" the links in the carousel-indicators are not working!

**Comment by Bunnyfield** [comment]
Fixed and pushed
