### ISSUE TITLE
Provided SVG files needs to be integrated

### ISSUE THREAD

**Issue by tdeuling** [typo3-themes/themes_gridelements#32]
See: https://github.com/typo3-themes/themes_gridelements/tree/master/Resources/Public/Icons/GridElements

**Comment by jousch** [comment]
I've recreated your beLayout icons as svg: https://github.com/jousch/TYPO3-Distribution/commit/48f74b165e80b18b0681f79841b6a14c7cb9c81e (see also the provided ai file)

cheers

**Comment by tdeuling** [comment]
Thanks for sharing. I've just integrate them :)
