### ISSUE TITLE
Remove deprecated includeLibs.t3jquery

### ISSUE THREAD

**Issue by freshworkx** [typo3-themes/themes_gridelements#34]
Please remove deprecated "includeLibs.t3jquery" in themes_gridelements/Configuration/TypoScript/setup.txt, as mentioned in typo3conf/ext/t3jquery/class.tx_t3jquery.php

**Comment by kaystrobach** [comment]
@freshworkx how about providing a small merge request? should be a no brainer :smile:

**Comment by Bunnyfield** [comment]
Done
