### ISSUE TITLE
Inheritance for "themes_gridelements"

### ISSUE THREAD

**Issue by responseinformationsdesign** [typo3-themes/themes_gridelements#35]
How should inheritance be handled for gridlements? Where should replaced/extended typoscripts or flexforms be located? Needless to say that putting them into the themes_gridelements file struture wouldn´t be update safe.

**Comment by tdeuling** [comment]
It should be located in your own theme, for example:
theme_bootstrap_slate/Configuration/Elements/Flexforms
theme_bootstrap_slate/Configuration/Elements/PageTS
theme_bootstrap_slate/Configuration/Elements/TypoScript

**Comment by tdeuling** [comment]
Your themes setup.txt gets one more line like:
```<INCLUDE_TYPOSCRIPT: source="DIR:EXT:theme_bootstrap_slate/Configuration/Elements/TypoScript" extensions="setupts">```

Same in the tsconfig.txt of your theme:
```<INCLUDE_TYPOSCRIPT: source="DIR:EXT:theme_bootstrap_slate/Configuration/Elements/PageTS" extensions="pagets">```

For example, overwriting the accordion template within ```theme_bootstrap_slate/Configuration/Elements/TypoScript/Accordion.setupts``` with:
```
lib.gridelements {
	accordion {
		cObject {
			file = EXT:theme_bootstrap_slate/Resources/Private/Partials/Elements/Accordion/Accordion.html
		}
	}
}
tt_content.gridelements_pi1.20.10.setup.accordion < lib.gridelements.accordion
```

**Comment by responseinformationsdesign** [comment]
Thanks! This has already been realized. But where to put customized flexform files (I need additional variations in "2ColumnGrid.xml")?

**Comment by tdeuling** [comment]
![auswahl_001](https://cloud.githubusercontent.com/assets/1298841/12986441/93c15a46-d0f7-11e5-9839-0cc3555a36fd.png)

**Comment by responseinformationsdesign** [comment]
Have a look at the file structure of "theme_bootstrap_slate". There is no level "Elements" (for the moment). Also confusing: In your screenshot folders "Elements", "PageTS" and "TypoScript" would be at the same level. As written above "PageTS" and "TypoScript" should be subfolders of "Elements".

**Comment by tdeuling** [comment]
It's absolutely the same structure like in themes_gridelements!

**Comment by responseinformationsdesign** [comment]
Then it should be corrected for the current version of "themes_bootstrap_slate" in GitHub. Do you agree?

**Comment by Bunnyfield** [comment]
It's correct liket that, since the folder "Elements" only has to be created if you want to override existing elements or add your own elements. Otherwise there is no  need for this folder. But IF you create it, you will need a PageTS and a TypoScript section in there as well, which will hold the backend and frontend setups for those elements. - The fact that there is no such folder in theme_bootstrap_slate just indicates that this theme does neither add nor change any kind of element.

**Comment by kaystrobach** [comment]
:+1:

Von meinem iPad gesendet
